src/Entity/EtapeCircuit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EtapeCircuitRepository")
 */
class EtapeCircuit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ville")
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_ville_etape;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Circuit")
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_circuit_etape;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree_etape;

    /**
     * @ORM\Column(type="integer")
     */
    private $ordre_etape;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeVilleEtape(): ?ville
    {
        return $this->code_ville_etape;
    }

    public function setCodeVilleEtape(?ville $code_ville_etape): self
    {
        $this->code_ville_etape = $code_ville_etape;

        return $this;
    }

    public function getCodeCircuitEtape(): ?circuit
    {
        return $this->code_circuit_etape;
    }

    public function setCodeCircuitEtape(?circuit $code_circuit_etape): self
    {
        $this->code_circuit_etape = $code_circuit_etape;

        return $this;
    }

    public function getDureeEtape(): ?int
    {
        return $this->duree_etape;
    }

    public function setDureeEtape(int $duree_etape): self
    {
        $this->duree_etape = $duree_etape;

        return $this;
    }

    public function getOrdreEtape(): ?int
    {
        return $this->ordre_etape;
    }

    public function setOrdreEtape(int $ordre_etape): self
    {
        $this->ordre_etape = $ordre_etape;

        return $this;
    }
}

src/Form/EtapeCircuitType.php
<?php

namespace App\Form;

use App\Entity\EtapeCircuit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtapeCircuitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('duree_etape')
            ->add('ordre_etape')
            ->add('code_ville_etape')
            ->add('code_circuit_etape')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EtapeCircuit::class,
        ]);
    }
}

src/Controller/EtapeCircuitController.php
<?php

namespace App\Controller;

use App\Entity\EtapeCircuit;
use App\Form\EtapeCircuitType;
use App\Repository\EtapeCircuitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/etape/circuit")
 */
class EtapeCircuitController extends AbstractController
{
    /**
     * @Route("/", name="etape_circuit_index", methods={"GET"})
     */
    public function index(EtapeCircuitRepository $etapeCircuitRepository): Response
    {
        return $this->render('etape_circuit/index.html.twig', [
            'etape_circuits' => $etapeCircuitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="etape_circuit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $etapeCircuit = new EtapeCircuit();
        $form = $this->createForm(EtapeCircuitType::class, $etapeCircuit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($etapeCircuit);
            $entityManager->flush();

            return $this->redirectToRoute('circuit_index');
        }

        return $this->render('etape_circuit/new.html.twig', [
            'etape_circuit' => $etapeCircuit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etape_circuit_show", methods={"GET"})
     */
    public function show(EtapeCircuit $etapeCircuit): Response
    {
        return $this->render('etape_circuit/show.html.twig', [
            'etape_circuit' => $etapeCircuit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="etape_circuit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, EtapeCircuit $etapeCircuit): Response
    {
        $form = $this->createForm(EtapeCircuitType::class, $etapeCircuit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('circuit_index');
        }

        return $this->render('etape_circuit/edit.html.twig', [
            'etape_circuit' => $etapeCircuit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etape_circuit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, EtapeCircuit $etapeCircuit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etapeCircuit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($etapeCircuit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('circuit_index');
    }
}

templates/etape_circuit/_delete_form.html.twig
<form method="post" action="{{ path('etape_circuit_delete', {'id': etape_circuit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etape_circuit.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/etape_circuit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/etape_circuit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit EtapeCircuit{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
    <h1>Edit EtapeCircuit</h1>
    <br>
    {{ include('etape_circuit/_form.html.twig', {'button_label': 'Update'}) }}
    <br>
    {{ include('etape_circuit/_delete_form.html.twig') }}
    <br>
    <a href="{{ path('circuit_index') }}" >back to list</a>

{% endblock %}

templates/etape_circuit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EtapeCircuit index{% endblock %}

{% block body %}
    <h1>EtapeCircuit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Duree_etape</th>
                <th>Ordre_etape</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etape_circuit in etape_circuits %}
            <tr>
                <td>{{ etape_circuit.id }}</td>
                <td>{{ etape_circuit.dureeEtape }}</td>
                <td>{{ etape_circuit.ordreEtape }}</td>
                <td>
                    <a href="{{ path('etape_circuit_show', {'id': etape_circuit.id}) }}">show</a>
                    <a href="{{ path('etape_circuit_edit', {'id': etape_circuit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('etape_circuit_new') }}">Create new</a>
{% endblock %}

templates/etape_circuit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New EtapeCircuit{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br>
    <h1>Create new EtapeCircuit</h1>
    <br>

    {{ include('etape_circuit/_form.html.twig') }}

    <a href="{{ path('etape_circuit_index') }}" >back to list</a>
{% endblock %}

templates/etape_circuit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}EtapeCircuit{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}

    </style>
    <br><br>
    <h1>EtapeCircuit</h1>
    <br>

    <table class="table table-sm table-dark table table-striped ">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etape_circuit.id }}</td>
            </tr>
            <tr>
                <th>Duree_etape</th>
                <td>{{ etape_circuit.dureeEtape }}</td>
            </tr>
            <tr>
                <th>Ordre_etape</th>
                <td>{{ etape_circuit.ordreEtape }}</td>
            </tr>
        </tbody>
    </table>
    {{ include('etape_circuit/_delete_form.html.twig') }}
    <br>
    <a href="{{ path('etape_circuit_edit', {'id': etape_circuit.id}) }}">edit</a>
    <br>
    <a href="{{ path('circuit_index') }}">back to list</a>

{% endblock %}