src/Entity/Ville.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VilleRepository")
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $des_ville;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Destination")
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_dest;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeVille(): ?string
    {
        return $this->code_ville;
    }

    public function setCodeVille(string $code_ville): self
    {
        $this->code_ville = $code_ville;

        return $this;
    }

    public function getDesVille(): ?string
    {
        return $this->des_ville;
    }

    public function setDesVille(string $des_ville): self
    {
        $this->des_ville = $des_ville;

        return $this;
    }

    public function getCodeDest(): ?Destination
    {
        return $this->code_dest;
    }

    public function setCodeDest(?Destination $code_dest): self
    {
        $this->code_dest = $code_dest;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getCodeVille();
    }
}

src/Form/VilleType.php
<?php

namespace App\Form;

use App\Entity\Ville;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VilleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code_ville')
            ->add('des_ville')
            ->add('image')
            ->add('code_dest')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ville::class,
        ]);
    }
}

src/Controller/VilleController.php
<?php

namespace App\Controller;

use App\Entity\Ville;
use App\Form\VilleType;
use App\Repository\VilleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ville")
 */
class VilleController extends AbstractController
{
    /**
     * @Route("/", name="ville_index", methods={"GET"})
     */
    public function index(VilleRepository $villeRepository): Response
    {
        return $this->render('ville/index.html.twig', [
            'villes' => $villeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ville_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ville = new Ville();
        $form = $this->createForm(VilleType::class, $ville);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ville);
            $entityManager->flush();

            return $this->redirectToRoute('destination_index');
        }

        return $this->render('ville/new.html.twig', [
            'ville' => $ville,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ville_show", methods={"GET"})
     */
    public function show(Ville $ville): Response
    {
        return $this->render('ville/show.html.twig', [
            'ville' => $ville,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ville_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ville $ville): Response
    {
        $form = $this->createForm(VilleType::class, $ville);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('destination_index');
        }

        return $this->render('ville/edit.html.twig', [
            'ville' => $ville,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ville_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ville $ville): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ville->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ville);
            $entityManager->flush();
        }

        return $this->redirectToRoute('destination_index');
    }

}

templates/ville/_delete_form.html.twig
<style>
    body{background-color: #dfdfdf}
    table{text-align: center;}
</style>
<br><br>
<form method="post" action="{{ path('ville_delete', {'id': ville.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ville.id) }}">
    <button class="btn btn-primary" >Delete</button>
</form>

templates/ville/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ville/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ville{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
    </style>
    <br>
    <h1>Edit Ville</h1>
    <br>

    {{ include('ville/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('ville/_delete_form.html.twig') }}
    <br> <br>
    <a href="{{ path('destination_index') }}" class="btn btn-primary">back to list</a>

{% endblock %}

templates/ville/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ville index{% endblock %}

{% block body %}
    <h1>Ville index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code_ville</th>
                <th>Des_ville</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ville in villes %}
            <tr>
                <td>{{ ville.id }}</td>
                <td>{{ ville.codeVille }}</td>
                <td>{{ ville.desVille }}</td>
                <td>{{ ville.image }}</td>
                <td>
                    <a href="{{ path('ville_show', {'id': ville.id}) }}">show</a>
                    <a href="{{ path('ville_edit', {'id': ville.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ville_new') }}">Create new</a>
{% endblock %}

templates/ville/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ville{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
    <h1>Create new Ville</h1>
<br>
    {{ include('ville/_form.html.twig') }}

    <a href="{{ path('ville_index') }}" class="btn btn-primary">back to list</a>
{% endblock %}

templates/ville/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ville{% endblock %}

{% block body %}
    <h1>Ville</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ville.id }}</td>
            </tr>
            <tr>
                <th>Code_ville</th>
                <td>{{ ville.codeVille }}</td>
            </tr>
            <tr>
                <th>Des_ville</th>
                <td>{{ ville.desVille }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ ville.image }}</td>
            </tr>
        </tbody>
    </table>



    {{ include('ville/_delete_form.html.twig') }}
    <a href="{{ path('ville_edit', {'id': ville.id}) }}">edit</a>
    <br>
    <a href="{{ path('ville_index') }}">back to list</a>

{% endblock %}