src/Entity/Circuit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CircuitRepository")
 */
class Circuit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_circuit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $des_circuit;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree_circuit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeCircuit(): ?string
    {
        return $this->code_circuit;
    }

    public function setCodeCircuit(string $code_circuit): self
    {
        $this->code_circuit = $code_circuit;

        return $this;
    }

    public function getDesCircuit(): ?string
    {
        return $this->des_circuit;
    }

    public function setDesCircuit(string $des_circuit): self
    {
        $this->des_circuit = $des_circuit;

        return $this;
    }

    public function getDureeCircuit(): ?int
    {
        return $this->duree_circuit;
    }

    public function setDureeCircuit(int $duree_circuit): self
    {
        $this->duree_circuit = $duree_circuit;

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getCodeCircuit();
    }
}

src/Form/CircuitType.php
<?php

namespace App\Form;

use App\Entity\Circuit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CircuitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code_circuit')
            ->add('des_circuit')
            ->add('duree_circuit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Circuit::class,
        ]);
    }
}

src/Controller/CircuitController.php
<?php

namespace App\Controller;

use App\Entity\Circuit;
use App\Form\CircuitType;
use App\Repository\CircuitRepository;
use App\Repository\EtapeCircuitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/circuit")
 */
class CircuitController extends AbstractController
{
    private $rep_etape;

    public  function __construct(EtapeCircuitRepository $rep_etape_param)
    {
        $this->rep_etape=$rep_etape_param;
    }

    /**
     * @Route("/", name="circuit_index", methods={"GET"})
     * @param CircuitRepository $circuitRepository
     * @return Response
     */
    public function index(CircuitRepository $circuitRepository): Response
    {
        return $this->render('circuit/index.html.twig', [
            'circuits' => $circuitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="circuit_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $circuit = new Circuit();
        $form = $this->createForm(CircuitType::class, $circuit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($circuit);
            $entityManager->flush();

            return $this->redirectToRoute('circuit_index');
        }

        return $this->render('circuit/new.html.twig', [
            'circuit' => $circuit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="circuit_show", methods={"GET"})
     * @param Circuit $circuit
     * @return Response
     */
    public function show(Circuit $circuit): Response

    {
        $etapes= $this->rep_etape->findByCircuit($circuit) ;

        return $this->render('circuit/show.html.twig', [
            'circuit' => $circuit,
            'etapes' => $etapes,]);
    }
    /**
     * @Route("/{id}/edit", name="circuit_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Circuit $circuit
     * @return Response
     */
    public function edit(Request $request, Circuit $circuit): Response
    {
        $form = $this->createForm(CircuitType::class, $circuit);
        $form->handleRequest($request);
        $etapes= $this->rep_etape->findByCircuit($circuit) ;

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('circuit_index');
        }
        return $this->render('circuit/edit.html.twig', [
            'circuit' => $circuit,
            'etapes' => $etapes,

            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="circuit_delete", methods={"DELETE"})
     * @param Request $request
     * @param Circuit $circuit
     * @return Response
     */
    public function delete(Request $request, Circuit $circuit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$circuit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($circuit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('circuit_index');
    }
}

templates/circuit/_delete_form.html.twig
<form method="post" action="{{ path('circuit_delete', {'id': circuit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ circuit.id) }}">
    <button class="btn" style="color: #007bff">Delete</button>
</form>

templates/circuit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/circuit/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Edit Circuit{% endblock %}
{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
    <h1>Edit Circuit</h1>
    {{ include('circuit/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('circuit/_delete_form.html.twig') }}
<br>
    <h2 style="text-align: center">Liste des etapes de  circuit {{ circuit.getDesCircuit() }}</h2>
    <table class="table table-sm table-dark table table-striped ">
        <thead>

        <tr>
            <th>Code ville etape</th> <th>Circuit etape</th> <th>Durée etape</th> <th>Ordre etape</th>
            {% if is_granted('ROLE_ADMIN') %} <th>Actions</th> {% endif %}
        </tr>

        </thead>
        <tbody>
        {% for etape in etapes %}
            <tr>
                <td>{{ etape.codeVilleEtape() }}</td>
                <td>{{ etape.codeCircuitEtape() }}</td>
                <td >{{ etape.dureeEtape() }}</td>
                <td>{{ etape.ordreEtape() }}</td>
                {% if is_granted('ROLE_ADMIN') %}
                    <td>
                        <a href="{{ path('etape_circuit_delete', {'id': etape.id}) }}">delete</a>
                        <a href="{{ path('etape_circuit_edit', {'id': etape.id}) }}">edit</a>
                    </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}


        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('etape_circuit_new') }}">Create new etape...</a>
    {% endif %}
    <br>
    <a href="{{ path('circuit_index') }}" class="btn btn-primary">back to list</a>

{% endblock %}

templates/circuit/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}TravelNow::Circuits{% endblock %}
{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
    <h2 style="text-align: center">Liste des circuits</h2>
    <br><br>
    <table class="table table-sm table-dark table table-striped " >
        <thead>
            <tr>
                {% if is_granted('ROLE_ADMIN') %}
                <th>Code circuit</th>
                {% endif %}
                <th>Circuit</th><th>Durée circuit</th>
                {% if is_granted('ROLE_ADMIN') %}
                <th>actions</th>
                {% endif %}


            </tr>
        </thead>
        <tbody>
        {% for circuit in circuits %}
            <tr>
                {% if is_granted('ROLE_ADMIN') %}<td>{{ circuit.codeCircuit }}</td>{% endif %}
                <td> <a href="{{ path('circuit_show', {'id': circuit.id}) }}">{{ circuit.desCircuit }}</a> </td>
                <td>{{ circuit.dureeCircuit }}</td>
                <td>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a>{{ include('circuit/_delete_form.html.twig') }}</a>
                    <a href="{{ path('circuit_edit', {'id': circuit.id}) }}">edit</a>
                    {% endif %}
                </td>

            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('circuit_new') }}">Create new circuit</a>
    {% endif %}
{% endblock %}

templates/circuit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Circuit{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
    <h1>Create new Circuit</h1>

    {{ include('circuit/_form.html.twig') }}

    <a href="{{ path('circuit_index') }}" >back to list</a>
{% endblock %}

templates/circuit/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Circuit{% endblock %}
{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
<h2>Circuit {{ circuit.desCircuit }} </h2>
    <br><br>
    <table class="table table-sm table-dark table table-striped ">
        <tbody>
        {% if is_granted('ROLE_ADMIN') %}
            <tr>
                <th>Id</th> <td>{{ circuit.id }}</td>
            </tr>
            <tr>
                <th>Code_circuit</th> <td>{{ circuit.codeCircuit }}</td>
            </tr>
        {% endif %}
            <tr>
                <th>Circuit</th> <td>{{ circuit.desCircuit }}</td>
            </tr>
            <tr>
                <th>Durée circuit</th> <td>{{ circuit.dureeCircuit }}</td>
            </tr>
        </tbody>
    </table>
    <br><br>
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('circuit_edit', {'id': circuit.id}) }}">edit</a>
    {{ include('circuit/_delete_form.html.twig') }}
    {% endif %}
    <h2 style="text-align: center">Liste des etapes de  circuit {{ circuit.getDesCircuit() }}</h2>
    <br><br>

    <table class="table table-sm table-dark table table-striped ">
        <thead>

        <tr>
            <th>Code Ville </th> <th>Circuit etape</th> <th>Durée etape</th> <th>Ordre etape</th>
            {% if is_granted('ROLE_ADMIN') %} <th>Actions</th> {% endif %}
        </tr>

        </thead>
        <tbody>
        {% for etape in etapes %}
        <tr>
            <td>{{ etape.codeVilleEtape() }}</td>
            <td>{{ etape.codeCircuitEtape() }}</td>
            <td >{{ etape.dureeEtape() }}</td>
            <td>{{ etape.ordreEtape() }}</td>
            {% if is_granted('ROLE_ADMIN') %}
            <td>
                <a href="{{ path('etape_circuit_delete', {'id': etape.id}) }}">delete</a>
                <a href="{{ path('etape_circuit_edit', {'id': etape.id}) }}">edit</a>
            </td>
            {% endif %}
        </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}


        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('etape_circuit_new') }}">Create new etape...</a>
    {% endif %}
    <br><br>
    <a href="{{ path('circuit_index') }}" class="btn btn-primary">back to list</a>

{% endblock %}