src/Entity/Destination.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DestinationRepository")
 */
class Destination
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_dest;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $des_dest;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeDest(): ?int
    {
        return $this->code_dest;
    }

    public function setCodeDest(int $code_dest): self
    {
        $this->code_dest = $code_dest;

        return $this;
    }

    public function getDesDest(): ?string
    {
        return $this->des_dest;
    }

    public function setDesDest(string $des_dest): self
    {
        $this->des_dest = $des_dest;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getCodeDest();
    }
}

src/Form/DestinationType.php
<?php

namespace App\Form;

use App\Entity\Destination;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DestinationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code_dest')
            ->add('des_dest')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Destination::class,
        ]);
    }
}

src/Controller/DestinationController.php
<?php

namespace App\Controller;

use App\Entity\Destination;
use App\Form\DestinationType;
use App\Repository\DestinationRepository;
use App\Repository\VilleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/destination")
 */
class DestinationController extends AbstractController
{
    private $rep_ville;

    public  function __construct(VilleRepository $rep_ville_param)
    {
        $this->rep_ville=$rep_ville_param;
    }


    /**
     * @Route("/", name="destination_index", methods={"GET"})
     * @param DestinationRepository $destinationRepository
     * @return Response
     */
    public function index(DestinationRepository $destinationRepository): Response
    {
        return $this->render('destination/index.html.twig', [
            'destinations' => $destinationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="destination_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $destination = new Destination();
        $form = $this->createForm(DestinationType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($destination);
            $entityManager->flush();

            return $this->redirectToRoute('destination_index');
        }

        return $this->render('destination/new.html.twig', [
            'destination' => $destination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="destination_show", methods={"GET"})
     * @param Destination $destination
     * @return Response
     */
    public function show(Destination $destination): Response
    {
        $villes=$this->rep_ville->findByDestination($destination);

        return $this->render('destination/show.html.twig', [
            'destination' => $destination,
            'villes' => $villes
        ]);
    }


    /**
     * @Route("/{id}/edit", name="destination_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Destination $destination
     * @return Response
     */
    public function edit(Request $request, Destination $destination): Response
    {
        $form = $this->createForm(DestinationType::class, $destination);
        $form->handleRequest($request);

        $villes=$this->rep_ville->findByDestination($destination);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('destination_index');
        }

        return $this->render('destination/edit.html.twig',
            [
                'destination' => $destination,
                'villes' => $villes,
                'form'=> $form -> createView(),
            ]);
    }

    /**
     * @Route("/{id}", name="destination_delete", methods={"DELETE"})
     * @param Request $request
     * @param Destination $destination
     * @return Response
     */
    public function delete(Request $request, Destination $destination): Response
    {
        if ($this->isCsrfTokenValid('delete'.$destination->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($destination);
            $entityManager->flush();
        }

        return $this->redirectToRoute('destination_index');
    }
}

templates/destination/_delete_form.html.twig
<form method="post" action="{{ path('destination_delete', {'id': destination.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ destination.id) }}">
    <button class="btn" style="color: #007bff;">Delete</button>
</form>

templates/destination/_form.html.twig
{% if form is defined %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{% endif %}

templates/destination/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Destination{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}

        img{
            height:150px;
            width:100%;
        }

        .item{
            padding-left:5px;
            padding-right:5px;
        }
        .item-card{
            transition:0.5s;
            cursor:pointer;
        }
        .item-card-title{
            font-size:15px;
            transition:1s;
            cursor:pointer;
        }
        .item-card-title i{
            font-size:15px;
            transition:1s;
            cursor:pointer;
            color:#ffa710
        }
        .card-title i:hover{
            transform: scale(1.25) rotate(100deg);
            color:#18d4ca;

        }
        .card:hover{
            transform: scale(1.05);
            box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
        }
        .card-text{
            height:80px;
        }

        .card::before, .card::after {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            transform: scale3d(0, 0, 1);
            transition: transform .3s ease-out 0s;
            background: rgba(255, 255, 255, 0.1);
            content: '';
            pointer-events: none;
        }
        .card::before {
            transform-origin: left top;
        }
        .card::after {
            transform-origin: right bottom;
        }
        .card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
            transform: scale3d(1, 1, 1);
        }
    </style>
    <h1>Edit Destination</h1>

     {{ include('destination/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('destination/_delete_form.html.twig') }}

    <h2>Liste des villes de {{ destination.getDesDest() }}</h2>
    <div class="container mt-2">

        <div class="row">
            {% for ville in villes %}
            <div class="col-md-3 col-sm-6 item">
                <div class="card item-card card-block">
                    <h6 class="card-title text-right"><a href="{{ path('ville_edit', {'id': ville.id}) }}" >edit</a></h6>
                    <h6 class="card-title text-right"><a href="{{ path('ville_delete', {'id': ville.id}) }}">delete</a> </h6>
                    <img src="{{ ville.image }}" >
                    <h3>{{ ville.getDesVille() }}</h3>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('ville_new') }}">Add ville...</a>
    {% endif %}
    <br>
    <a href="{{ path('destination_index') }}" class="btn btn-primary">back to list</a>


{% endblock %}

templates/destination/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Destination index{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}

        img{
            height:150px;
            width:100%;
        }

        .item{
            padding-left:5px;
            padding-right:5px;
        }
        .item-card{
            transition:0.5s;
            cursor:pointer;
        }
        .item-card-title{
            font-size:15px;
            transition:1s;
            cursor:pointer;
        }
        .item-card-title i{
            font-size:15px;
            transition:1s;
            cursor:pointer;
            color:#ffa710
        }
        .card-title i:hover{
            transform: scale(1.25) rotate(100deg);
            color:#18d4ca;

        }
        .card:hover{
            transform: scale(1.05);
            box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
        }
        .card-text{
            height:80px;
        }

        .card::before, .card::after {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            transform: scale3d(0, 0, 1);
            transition: transform .3s ease-out 0s;
            background: rgba(255, 255, 255, 0.1);
            content: '';
            pointer-events: none;
        }
        .card::before {
            transform-origin: left top;
        }
        .card::after {
            transform-origin: right bottom;
        }
        .card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
            transform: scale3d(1, 1, 1);
        }
    </style>
    <br><br>

    <h2 style="text-align: center">Liste des destinations </h2>
    <br>

    <div class="container mt-2">

        <div class="row">
            {% for destination in destinations %}

            <div class="col-md-3 col-sm-6 item">
                <div class="card item-card card-block">
                    {% if is_granted('ROLE_ADMIN') %}

                    <h6 class="card-title text-right"><a href="{{ path('destination_edit', {'id': destination.id}) }}" >Modifier</a></h6>
                    <h6 class="card-title text-right" >    {{ include('destination/_delete_form.html.twig') }} </h6>
                    {% endif %}

                    <a href="{{ path('destination_show', {'id': destination.id}) }}"> <img src="{{ destination.image }}" > </a>
                    <h3 >{{ destination.desDest }}</h3>
                    <p class="card-text">Votre destination de rêve !</p>
                </div>
            </div>
            {% else %}
                <tr>
                    <h4>Aucune destination!</h4>
            {% endfor %}

        </div>
    </div>


    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('destination_new') }}" class="h5">Ajouter Destination...</a>
    {% endif %}
{% endblock %}

templates/destination/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Destination{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}
        table{text-align: center;}
    </style>
    <br><br>
    <h1>Create new Destination</h1>

    {{ include('destination/_form.html.twig') }}

    <a href="{{ path('destination_index') }}" class="btn btn-primary">back to list</a>
{% endblock %}

templates/destination/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Destination{% endblock %}

{% block body %}
    <style>
        body{background-color: #dfdfdf}

        table{text-align: center;}

        img{
            height:150px;
            width:100%;
        }

        .item{
            padding-left:5px;
            padding-right:5px;
        }
        .item-card{
            transition:0.5s;
            cursor:pointer;
        }
        .item-card-title{
            font-size:15px;
            transition:1s;
            cursor:pointer;
        }
        .item-card-title i{
            font-size:15px;
            transition:1s;
            cursor:pointer;
            color:#ffa710
        }
        .card-title i:hover{
            transform: scale(1.25) rotate(100deg);
            color:#18d4ca;

        }
        .card:hover{
            transform: scale(1.05);
            box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
        }
        .card-text{
            height:80px;
        }

        .card::before, .card::after {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            transform: scale3d(0, 0, 1);
            transition: transform .3s ease-out 0s;
            background: rgba(255, 255, 255, 0.1);
            content: '';
            pointer-events: none;
        }
        .card::before {
            transform-origin: left top;
        }
        .card::after {
            transform-origin: right bottom;
        }
        .card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
            transform: scale3d(1, 1, 1);
        }
    </style>
    <br>
    <h2 style="text-align: center">Destination</h2>
<br>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-3 col-sm-6 item">
                <div class="card item-card card-block">
                    <img src="{{ destination.image }}" >
                    <h3 >{{ destination.desDest }}</h3>
                </div>
            </div>
        </div>
    </div>

<br>

    <h2 style="text-align: center">Liste des villes de {{ destination.getDesDest() }}</h2>
    <br>

    <div class="container mt-2">

        <div class="row">
            {% for ville in villes %}
            <div class="col-md-3 col-sm-6 item">
                <div class="card item-card card-block">
                    {% if is_granted('ROLE_ADMIN') %}
                    <h6 class="card-title text-right"><a href="{{ path('ville_edit', {'id': ville.id}) }}" >edit</a></h6>
                    <h6 class="card-title text-right"><a href="{{ path('ville_delete', {'id': ville.id}) }}">delete</a> </h6>
                    {% endif %}
                    <img src="{{ ville.image }}" >
                    <h3>{{ ville.getDesVille() }}</h3>
                </div>
            </div>
            {% else %}

                <h4>Aucune ville!</h4>
                {% endfor %}

        </div>
    </div>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('ville_new') }}" class="h5">Add Ville...</a>
    {% endif %}
    <br><br>
    <a href="{{ path('destination_index') }}" class="btn btn-primary">back to list</a>










{% endblock %}